/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as chatRouteRouteImport } from './routes/(chat)/route'
import { Route as chatIndexRouteImport } from './routes/(chat)/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const chatRouteRoute = chatRouteRouteImport.update({
  id: '/(chat)',
  getParentRoute: () => rootRouteImport,
} as any)
const chatIndexRoute = chatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => chatRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof chatIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof chatIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(chat)': typeof chatRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/(chat)/': typeof chatIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/api/$' | '/' | '/api/auth/$' | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/api/$' | '/' | '/api/auth/$' | '/api/rpc/$'
  id:
    | '__root__'
    | '/(chat)'
    | '/(auth)/login'
    | '/api/$'
    | '/(chat)/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  chatRouteRoute: typeof chatRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(chat)': {
      id: '/(chat)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof chatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(chat)/': {
      id: '/(chat)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof chatIndexRouteImport
      parentRoute: typeof chatRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface chatRouteRouteChildren {
  chatIndexRoute: typeof chatIndexRoute
}

const chatRouteRouteChildren: chatRouteRouteChildren = {
  chatIndexRoute: chatIndexRoute,
}

const chatRouteRouteWithChildren = chatRouteRoute._addFileChildren(
  chatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  chatRouteRoute: chatRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
